name: Check & Format

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Rust & TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          make frontend_preinstall
          make frontend
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: TypeScript Check
        run: |
          pnpm -C frontend check

      - name: Prettier Check
        run: |
          pnpm -C frontend fmt:check

      - name: Clippy Check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace -- -D warnings

      - name: Rustfmt Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
